version: '3.9'

services:
  go-app:
    container_name: go-app2
    image: ibra/go-app:1.0.1
    build: .
    environment:
      DATABASE_URL: "host=go_db user=postgres password=postgres dbname=postgres sslmode=disable"
    ports:
      - "8001:8001"
    depends_on:
      - go_db
  go_db:
    container_name: go_db2
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:  
  pgdata: {} 
  
networks:
  default:
    external:
      name: shared_network 


# services:
#   go-app:
#     container_name: go-app
#     image: ibra/go-app:1.0.1
#     build: .
#     environment:
#       DATABASE_URL: "host=go_db_users user=postgres password=postgres dbname=postgres sslmode=disable"
#     ports:
#       - "8001:8000"
#     depends_on:
#       - go_db_users

#   go_db_users:
#     container_name: go_db_users  # Ensure the name matches here
#     image: postgres:12
#     environment:
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_USER: postgres
#       POSTGRES_DB: postgres
#     ports:
#       - "5433:5432"
#     volumes:
#       - pgdata:/var/lib/postgresql/data

# volumes:  
#   pgdata: {}
